//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eulei.shop.ServiceShareArticle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShareArticleEntity", Namespace="http://schemas.datacontract.org/2004/07/eulei.shop.Services")]
    [System.SerializableAttribute()]
    public partial class ShareArticleEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShareArticleArticleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleAuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShareArticleCitedArticleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShareArticleCitedTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleFrameworkNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ShareArticleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShareArticleIsApplyReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShareArticleIsNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShareArticleIsPicThemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShareArticleIsShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShareArticleIsempField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleLabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShareArticleLastOperatDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleLastOperstorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleOperationgRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticlePictureTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticlePusherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticlePusherFriendNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ShareArticlePusherIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShareArticleSendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShareArticleShareDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShareArticleStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShareArticleStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareArticleUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShareArticleArticleID {
            get {
                return this.ShareArticleArticleIDField;
            }
            set {
                if ((this.ShareArticleArticleIDField.Equals(value) != true)) {
                    this.ShareArticleArticleIDField = value;
                    this.RaisePropertyChanged("ShareArticleArticleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleAuthor {
            get {
                return this.ShareArticleAuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleAuthorField, value) != true)) {
                    this.ShareArticleAuthorField = value;
                    this.RaisePropertyChanged("ShareArticleAuthor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShareArticleCitedArticleID {
            get {
                return this.ShareArticleCitedArticleIDField;
            }
            set {
                if ((this.ShareArticleCitedArticleIDField.Equals(value) != true)) {
                    this.ShareArticleCitedArticleIDField = value;
                    this.RaisePropertyChanged("ShareArticleCitedArticleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShareArticleCitedTypeID {
            get {
                return this.ShareArticleCitedTypeIDField;
            }
            set {
                if ((this.ShareArticleCitedTypeIDField.Equals(value) != true)) {
                    this.ShareArticleCitedTypeIDField = value;
                    this.RaisePropertyChanged("ShareArticleCitedTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleContent {
            get {
                return this.ShareArticleContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleContentField, value) != true)) {
                    this.ShareArticleContentField = value;
                    this.RaisePropertyChanged("ShareArticleContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleDescription {
            get {
                return this.ShareArticleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleDescriptionField, value) != true)) {
                    this.ShareArticleDescriptionField = value;
                    this.RaisePropertyChanged("ShareArticleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleFrameworkName {
            get {
                return this.ShareArticleFrameworkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleFrameworkNameField, value) != true)) {
                    this.ShareArticleFrameworkNameField = value;
                    this.RaisePropertyChanged("ShareArticleFrameworkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ShareArticleID {
            get {
                return this.ShareArticleIDField;
            }
            set {
                if ((this.ShareArticleIDField.Equals(value) != true)) {
                    this.ShareArticleIDField = value;
                    this.RaisePropertyChanged("ShareArticleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShareArticleIsApplyReturn {
            get {
                return this.ShareArticleIsApplyReturnField;
            }
            set {
                if ((this.ShareArticleIsApplyReturnField.Equals(value) != true)) {
                    this.ShareArticleIsApplyReturnField = value;
                    this.RaisePropertyChanged("ShareArticleIsApplyReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShareArticleIsNew {
            get {
                return this.ShareArticleIsNewField;
            }
            set {
                if ((this.ShareArticleIsNewField.Equals(value) != true)) {
                    this.ShareArticleIsNewField = value;
                    this.RaisePropertyChanged("ShareArticleIsNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShareArticleIsPicTheme {
            get {
                return this.ShareArticleIsPicThemeField;
            }
            set {
                if ((this.ShareArticleIsPicThemeField.Equals(value) != true)) {
                    this.ShareArticleIsPicThemeField = value;
                    this.RaisePropertyChanged("ShareArticleIsPicTheme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShareArticleIsShare {
            get {
                return this.ShareArticleIsShareField;
            }
            set {
                if ((this.ShareArticleIsShareField.Equals(value) != true)) {
                    this.ShareArticleIsShareField = value;
                    this.RaisePropertyChanged("ShareArticleIsShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShareArticleIsemp {
            get {
                return this.ShareArticleIsempField;
            }
            set {
                if ((this.ShareArticleIsempField.Equals(value) != true)) {
                    this.ShareArticleIsempField = value;
                    this.RaisePropertyChanged("ShareArticleIsemp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleLabel {
            get {
                return this.ShareArticleLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleLabelField, value) != true)) {
                    this.ShareArticleLabelField = value;
                    this.RaisePropertyChanged("ShareArticleLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShareArticleLastOperatDate {
            get {
                return this.ShareArticleLastOperatDateField;
            }
            set {
                if ((this.ShareArticleLastOperatDateField.Equals(value) != true)) {
                    this.ShareArticleLastOperatDateField = value;
                    this.RaisePropertyChanged("ShareArticleLastOperatDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleLastOperstor {
            get {
                return this.ShareArticleLastOperstorField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleLastOperstorField, value) != true)) {
                    this.ShareArticleLastOperstorField = value;
                    this.RaisePropertyChanged("ShareArticleLastOperstor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleOperationgRecord {
            get {
                return this.ShareArticleOperationgRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleOperationgRecordField, value) != true)) {
                    this.ShareArticleOperationgRecordField = value;
                    this.RaisePropertyChanged("ShareArticleOperationgRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticlePictureTitle {
            get {
                return this.ShareArticlePictureTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticlePictureTitleField, value) != true)) {
                    this.ShareArticlePictureTitleField = value;
                    this.RaisePropertyChanged("ShareArticlePictureTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticlePusher {
            get {
                return this.ShareArticlePusherField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticlePusherField, value) != true)) {
                    this.ShareArticlePusherField = value;
                    this.RaisePropertyChanged("ShareArticlePusher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticlePusherFriendName {
            get {
                return this.ShareArticlePusherFriendNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticlePusherFriendNameField, value) != true)) {
                    this.ShareArticlePusherFriendNameField = value;
                    this.RaisePropertyChanged("ShareArticlePusherFriendName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ShareArticlePusherID {
            get {
                return this.ShareArticlePusherIDField;
            }
            set {
                if ((this.ShareArticlePusherIDField.Equals(value) != true)) {
                    this.ShareArticlePusherIDField = value;
                    this.RaisePropertyChanged("ShareArticlePusherID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShareArticleSendDate {
            get {
                return this.ShareArticleSendDateField;
            }
            set {
                if ((this.ShareArticleSendDateField.Equals(value) != true)) {
                    this.ShareArticleSendDateField = value;
                    this.RaisePropertyChanged("ShareArticleSendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShareArticleShareDate {
            get {
                return this.ShareArticleShareDateField;
            }
            set {
                if ((this.ShareArticleShareDateField.Equals(value) != true)) {
                    this.ShareArticleShareDateField = value;
                    this.RaisePropertyChanged("ShareArticleShareDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShareArticleState {
            get {
                return this.ShareArticleStateField;
            }
            set {
                if ((this.ShareArticleStateField.Equals(value) != true)) {
                    this.ShareArticleStateField = value;
                    this.RaisePropertyChanged("ShareArticleState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShareArticleStatusID {
            get {
                return this.ShareArticleStatusIDField;
            }
            set {
                if ((this.ShareArticleStatusIDField.Equals(value) != true)) {
                    this.ShareArticleStatusIDField = value;
                    this.RaisePropertyChanged("ShareArticleStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleTitle {
            get {
                return this.ShareArticleTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleTitleField, value) != true)) {
                    this.ShareArticleTitleField = value;
                    this.RaisePropertyChanged("ShareArticleTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleType {
            get {
                return this.ShareArticleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleTypeField, value) != true)) {
                    this.ShareArticleTypeField = value;
                    this.RaisePropertyChanged("ShareArticleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareArticleUrl {
            get {
                return this.ShareArticleUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareArticleUrlField, value) != true)) {
                    this.ShareArticleUrlField = value;
                    this.RaisePropertyChanged("ShareArticleUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceShareArticle.IShareArticle")]
    public interface IShareArticle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareArticle/Push", ReplyAction="http://tempuri.org/IShareArticle/PushResponse")]
        bool Push(eulei.shop.ServiceShareArticle.ShareArticleEntity shareArticleEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareArticle/RePush", ReplyAction="http://tempuri.org/IShareArticle/RePushResponse")]
        bool RePush(eulei.shop.ServiceShareArticle.ShareArticleEntity shareArticleEntity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShareArticleChannel : eulei.shop.ServiceShareArticle.IShareArticle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShareArticleClient : System.ServiceModel.ClientBase<eulei.shop.ServiceShareArticle.IShareArticle>, eulei.shop.ServiceShareArticle.IShareArticle {
        
        public ShareArticleClient() {
        }
        
        public ShareArticleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShareArticleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShareArticleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShareArticleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Push(eulei.shop.ServiceShareArticle.ShareArticleEntity shareArticleEntity) {
            return base.Channel.Push(shareArticleEntity);
        }
        
        public bool RePush(eulei.shop.ServiceShareArticle.ShareArticleEntity shareArticleEntity) {
            return base.Channel.RePush(shareArticleEntity);
        }
    }
}
